# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insultor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0einsultor.proto\"\x16\n\x06String\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x16\n\x05\x41rray\x12\r\n\x05value\x18\x01 \x03(\t2i\n\x08Insultor\x12\x1e\n\tAddInsult\x12\x07.String\x1a\x06.Empty\"\x00\x12\x1e\n\nGetInsults\x12\x06.Empty\x1a\x06.Array\"\x00\x12\x1d\n\x08InsultMe\x12\x06.Empty\x1a\x07.String\"\x00\x62\x06proto3')



_STRING = DESCRIPTOR.message_types_by_name['String']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_ARRAY = DESCRIPTOR.message_types_by_name['Array']
String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), {
  'DESCRIPTOR' : _STRING,
  '__module__' : 'insultor_pb2'
  # @@protoc_insertion_point(class_scope:String)
  })
_sym_db.RegisterMessage(String)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'insultor_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), {
  'DESCRIPTOR' : _ARRAY,
  '__module__' : 'insultor_pb2'
  # @@protoc_insertion_point(class_scope:Array)
  })
_sym_db.RegisterMessage(Array)

_INSULTOR = DESCRIPTOR.services_by_name['Insultor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRING._serialized_start=18
  _STRING._serialized_end=40
  _EMPTY._serialized_start=42
  _EMPTY._serialized_end=49
  _ARRAY._serialized_start=51
  _ARRAY._serialized_end=73
  _INSULTOR._serialized_start=75
  _INSULTOR._serialized_end=180
# @@protoc_insertion_point(module_scope)
